/**
 * OceanEye Central Interconnected Mock Dataset
 * Contains linked data for Drones, VisionAI Detections, Coral Reefs,
 * Species Census, GIS Sectors, Alerts, Analytics, and Weather.
 */

const mockStore = {
  kpis: {
    activeDrones: 18,
    activeDronesDelta: "+2 Today",
    pollutionHotspots: 200,
    pollutionHotspotsDelta: "-8% this week",
    coralHealthIndex: 84.2,
    coralHealthDelta: "+1.4% vs last mo",
    waterQualityScore: 91,
    waterQualityDelta: "Optimal Grade A",
    environmentalRisk: "Low-Moderate",
    riskIndexScore: 32,
    speciesTracked: 120,
    activeMissions: 30,
    satelliteCoverage: "99.4%"
  },

  drones: [
    {
      id: "DR-001",
      name: "Triton Sentinel I",
      model: "AUV-X5 Deep Explorer",
      status: "ACTIVE",
      battery: 88,
      depth: 284,
      maxDepth: 1200,
      speed: 3.4,
      heading: 142,
      signal: 96,
      signalStatus: "EXCELLENT",
      mission: "MIS-001",
      missionName: "Plastic Pollution Survey",
      sector: "SEC-B4",
      latitude: 12.92453,
      longitude: 73.14482,
      cameraType: "4K Ultra HD",
      sonarType: "Side-Scan 450kHz",
      cameraStatus: "ONLINE",
      temperature: 18.4,
      pressure: 28.4,
      salinity: 35.2,
      oxygenLevel: 6.8,
      remainingTimeMin: 142,
      lastMaintenance: "2026-07-01T00:00:00Z",
      lastCommunication: "2026-07-24T08:42:17Z",
      assignedOperator: "Dr. Elena Rostova",
      streamUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
      batteryHistory: [92, 89, 85, 82, 88, 91, 88],
      missionHistory: ["MIS-023", "MIS-018", "MIS-012", "MIS-005"],
      maintenanceHistory: [
        { date: "2026-07-01T00:00:00Z", type: "Routine Inspection", notes: "All systems nominal" },
        { date: "2026-05-15T00:00:00Z", type: "Battery Replacement", notes: "Upgraded to Li-ion 5000mAh" }
      ]
    },
    {
      id: "DR-002",
      name: "Nautilus Scan II",
      model: "Glider-7 Micro-Sub",
      status: "ACTIVE",
      battery: 64,
      depth: 512,
      maxDepth: 2000,
      speed: 2.1,
      heading: 210,
      signal: 84,
      signalStatus: "GOOD",
      mission: "MIS-002",
      missionName: "Coral Reef Bleaching Audit",
      sector: "SEC-A2",
      latitude: 14.1124,
      longitude: 72.8441,
      cameraType: "8K Spectral",
      sonarType: "Multibeam 200kHz",
      cameraStatus: "ONLINE",
      temperature: 16.1,
      pressure: 51.2,
      salinity: 35.5,
      oxygenLevel: 6.2,
      remainingTimeMin: 98,
      lastMaintenance: "2026-06-20T00:00:00Z",
      lastCommunication: "2026-07-24T08:40:22Z",
      assignedOperator: "Dr. Marcus Chen",
      streamUrl: "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=800&q=80",
      batteryHistory: [78, 72, 68, 65, 70, 74, 64],
      missionHistory: ["MIS-021", "MIS-015", "MIS-008", "MIS-002"],
      maintenanceHistory: [
        { date: "2026-06-20T00:00:00Z", type: "Sensor Calibration", notes: "Spectral camera recalibrated" },
        { date: "2026-04-10T00:00:00Z", type: "Hull Inspection", notes: "Minor biofouling removed" }
      ]
    },
    {
      id: "DR-003",
      name: "Abyssal Watcher III",
      model: "ROV-Titan Trench Probe",
      status: "ACTIVE",
      battery: 92,
      depth: 1840,
      maxDepth: 4000,
      speed: 1.8,
      heading: 45,
      signal: 78,
      signalStatus: "STABLE",
      mission: "MIS-003",
      missionName: "Hydrothermal Vent Analysis",
      sector: "SEC-C1",
      latitude: 11.4589,
      longitude: 74.2210,
      cameraType: "Low-Light 4K",
      sonarType: "Synthetic Aperture",
      cameraStatus: "ONLINE",
      temperature: 4.2,
      pressure: 184.0,
      salinity: 36.1,
      oxygenLevel: 4.5,
      remainingTimeMin: 210,
      lastMaintenance: "2026-07-10T00:00:00Z",
      lastCommunication: "2026-07-24T08:38:45Z",
      assignedOperator: "Dr. Sarah Kim",
      streamUrl: "https://images.unsplash.com/photo-1559825481-12a05cc00344?auto=format&fit=crop&w=800&q=80",
      batteryHistory: [95, 93, 90, 88, 91, 94, 92],
      missionHistory: ["MIS-025", "MIS-019", "MIS-011", "MIS-003"],
      maintenanceHistory: [
        { date: "2026-07-10T00:00:00Z", type: "Pressure Vessel Test", notes: "Passed 4000m certification" },
        { date: "2026-05-20T00:00:00Z", type: "Thruster Replacement", notes: "Port thruster replaced" }
      ]
    },
    {
      id: "DR-004",
      name: "Poseidon EcoScan IV",
      model: "AUM-Spectra 3000",
      status: "CHARGING",
      battery: 28,
      depth: 0,
      maxDepth: 800,
      speed: 0.0,
      heading: 0,
      signal: 100,
      signalStatus: "EXCELLENT",
      mission: "MIS-004",
      missionName: "Docked at Vessel Research Alpha",
      sector: "SEC-B4",
      latitude: 12.9110,
      longitude: 73.1200,
      cameraType: "Multi-Spectral",
      sonarType: "Forward-Looking 100kHz",
      cameraStatus: "STANDBY",
      temperature: 26.5,
      pressure: 0,
      salinity: 34.9,
      oxygenLevel: 7.2,
      remainingTimeMin: 0,
      lastMaintenance: "2026-07-18T00:00:00Z",
      streamUrl: ""
    },
    {
      id: "DR-005",
      name: "Leviathan Scout V",
      model: "Bionic Stingray-X",
      status: "ACTIVE",
      battery: 77,
      depth: 145,
      maxDepth: 600,
      speed: 4.2,
      heading: 315,
      signal: 91,
      signalStatus: "EXCELLENT",
      mission: "MIS-005",
      missionName: "Blue Whale Pod Telemetry",
      sector: "SEC-A3",
      latitude: 13.8812,
      longitude: 71.9421,
      cameraType: "High-Speed 1080p",
      sonarType: "Doppler 300kHz",
      cameraStatus: "ONLINE",
      temperature: 22.8,
      pressure: 14.5,
      salinity: 35.0,
      oxygenLevel: 7.0,
      remainingTimeMin: 165,
      lastMaintenance: "2026-07-15T00:00:00Z",
      lastCommunication: "2026-07-24T08:41:33Z",
      assignedOperator: "Dr. Elena Rostova",
      streamUrl: "https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?auto=format&fit=crop&w=800&q=80",
      batteryHistory: [82, 79, 75, 72, 78, 80, 77],
      missionHistory: ["MIS-024", "MIS-017", "MIS-010", "MIS-005"],
      maintenanceHistory: [
        { date: "2026-07-15T00:00:00Z", type: "Propeller Check", notes: "Biofouling removed from propellers" },
        { date: "2026-05-25T00:00:00Z", type: "Acoustic Tag Calibration", notes: "Tagging system verified" }
      ]
    },
    {
      id: "DR-006",
      name: "Oceanus Patrol VI",
      model: "Drone-Interceptor 900",
      status: "MAINTENANCE",
      battery: 100,
      depth: 0,
      maxDepth: 1500,
      speed: 0.0,
      heading: 0,
      signal: 100,
      signalStatus: "STABLE",
      mission: "MIS-006",
      missionName: "Scheduled Thruster Calibration",
      sector: "SEC-BASE",
      latitude: 12.8900,
      longitude: 73.0500,
      cameraType: "Thermal Imaging",
      sonarType: "360° Sonar",
      cameraStatus: "OFFLINE",
      temperature: 27.1,
      pressure: 0,
      salinity: 34.8,
      oxygenLevel: 7.4,
      remainingTimeMin: 0,
      lastMaintenance: "2026-07-23T00:00:00Z",
      streamUrl: ""
    }
  ],

  visionDetections: [
    {
      id: "DET-001",
      type: "Abandoned Ghost Fishing Net",
      category: "PLASTIC_DEBRIS",
      confidence: 96.4,
      severity: "CRITICAL",
      sector: "SEC-B4",
      latitude: 12.9281,
      longitude: 73.1499,
      droneId: "DR-001",
      timestamp: "2026-07-23T18:15:32Z",
      dimensions: "14m x 6m",
      estimatedMassKg: 180,
      imageUrl: "https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=800&q=80",
      boundingBox: { x: 22, y: 18, width: 55, height: 60 },
      recommendation: "Deploy Vessel Alpha Recovery Team with winch gear to prevent marine entanglement.",
      status: "PENDING_RECOVERY"
    },
    {
      id: "DET-002",
      type: "Micro-Plastic Accumulation Slick",
      category: "MICROPLASTIC",
      confidence: 91.2,
      severity: "HIGH",
      sector: "SEC-A2",
      latitude: 14.1205,
      longitude: 72.8512,
      droneId: "DR-002",
      timestamp: "2026-07-23T17:42:10Z",
      dimensions: "450m radius",
      estimatedMassKg: 620,
      imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
      boundingBox: { x: 10, y: 15, width: 75, height: 70 },
      recommendation: "Notify Ocean Skimmer Drone Fleet for automated surface skim collection.",
      status: "INVESTIGATING"
    },
    {
      id: "DET-003",
      type: "Benthic Fuel Oil Residue",
      category: "CHEMICAL_SPILL",
      confidence: 88.7,
      severity: "HIGH",
      sector: "SEC-C1",
      latitude: 11.4620,
      longitude: 74.2255,
      droneId: "DR-003",
      timestamp: "2026-07-23T16:20:00Z",
      dimensions: "80m x 25m",
      estimatedMassKg: 340,
      imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80",
      boundingBox: { x: 30, y: 35, width: 40, height: 45 },
      recommendation: "Issue environmental warning flag for commercial shipping vessel cargo leak.",
      status: "ALERT_FLAGGED"
    },
    {
      id: "DET-004",
      type: "Industrial Chemical Drum Discard",
      category: "HAZARDOUS",
      confidence: 97.8,
      severity: "CRITICAL",
      sector: "SEC-A3",
      latitude: 13.8890,
      longitude: 71.9480,
      droneId: "DR-005",
      timestamp: "2026-07-23T15:05:45Z",
      dimensions: "1.2m x 0.8m",
      estimatedMassKg: 210,
      imageUrl: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80",
      boundingBox: { x: 40, y: 40, width: 25, height: 30 },
      recommendation: "High toxicity potential. Dispatch hazardous containment drone immediately.",
      status: "ACTION_REQUIRED"
    }
  ],

  coralReefs: [
    {
      id: "CRL-01",
      name: "Triton Barrier Reef Sanctuary",
      sector: "SEC-A2",
      latitude: 14.1100,
      longitude: 72.8400,
      healthScore: 88.5,
      bleachingRisk: "LOW",
      bleachingPercent: 4.2,
      surfaceTempC: 27.8,
      historicalTempAvg: 26.5,
      pHLevel: 8.14,
      turbidityNTU: 1.2,
      speciesDiversityIndex: 9.4,
      lastInspectionDate: "2026-07-22T00:00:00Z",
      trend: "IMPROVING",
      status: "PROTECTED_HEALTHY",
      imageUrl: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=800&q=80",
      assignedDrone: "DR-002",
      historicalHealth: [82.1, 84.3, 85.7, 86.9, 87.5, 88.2, 88.5],
      riskPrediction: "LOW",
      waterQuality: "EXCELLENT"
    },
    {
      id: "CRL-02",
      name: "Coral Atoll Sector Blue",
      sector: "SEC-B4",
      latitude: 12.9300,
      longitude: 73.1500,
      healthScore: 74.1,
      bleachingRisk: "MODERATE",
      bleachingPercent: 14.8,
      surfaceTempC: 29.4,
      historicalTempAvg: 27.1,
      pHLevel: 8.08,
      turbidityNTU: 2.8,
      speciesDiversityIndex: 8.1,
      lastInspectionDate: "2026-07-23T00:00:00Z",
      trend: "STABLE",
      status: "MONITORING_REQUIRED",
      imageUrl: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?auto=format&fit=crop&w=800&q=80",
      assignedDrone: "DR-001",
      historicalHealth: [71.2, 72.5, 73.1, 73.8, 74.0, 74.2, 74.1],
      riskPrediction: "MODERATE",
      waterQuality: "GOOD"
    },
    {
      id: "CRL-03",
      name: "Southern Shelf Deep Reef",
      sector: "SEC-C1",
      latitude: 11.4500,
      longitude: 74.2100,
      healthScore: 61.2,
      bleachingRisk: "HIGH",
      bleachingPercent: 28.6,
      surfaceTempC: 30.2,
      historicalTempAvg: 27.4,
      pHLevel: 7.98,
      turbidityNTU: 4.1,
      speciesDiversityIndex: 6.8,
      lastInspectionDate: "2026-07-21T00:00:00Z",
      trend: "DECLINING",
      status: "CRITICAL_BLEACHING",
      imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=800&q=80"
    }
  ],

  species: [
    {
      id: "SPC-001",
      commonName: "Blue Whale",
      scientificName: "Balaenoptera musculus",
      status: "ENDANGERED",
      populationEstimate: 12500,
      populationTrend: "INCREASING",
      primaryHabitat: "Epipelagic / Mesopelagic",
      sector: "SEC-A3",
      lastSighting: "2026-07-23T15:05:45Z",
      taggedIndividuals: 48,
      migrationStatus: "Northbound Annual Migration",
      threatLevel: "MODERATE",
      imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=800&q=80",
      description: "The largest marine mammal known. Pod tracks show healthy feeding behavior near nutrient upwellings.",
      preferredDepth: "0-300m",
      temperatureRange: "10-25°C",
      observationCount: 156,
      associatedSectors: ["SEC-A3", "SEC-D1", "SEC-D5"]
    },
    {
      id: "SPC-002",
      commonName: "Hawksbill Sea Turtle",
      scientificName: "Eretmochelys imbricata",
      status: "CRITICALLY_ENDANGERED",
      populationEstimate: 23000,
      populationTrend: "STABLE",
      primaryHabitat: "Coral Reefs & Seagrass Beds",
      sector: "SEC-A2",
      lastSighting: "2026-07-23T17:10:00Z",
      taggedIndividuals: 112,
      migrationStatus: "Nesting Season Active",
      threatLevel: "HIGH",
      imageUrl: "https://images.unsplash.com/photo-1544552866-d3ed42536cfd?auto=format&fit=crop&w=800&q=80",
      description: "Vulnerable to ghost nets and ocean plastic pollution. Monitored continuously by Triton DR-002.",
      preferredDepth: "0-50m",
      temperatureRange: "24-30°C",
      observationCount: 234,
      associatedSectors: ["SEC-A2", "SEC-A1", "SEC-B5"]
    },
    {
      id: "SPC-003",
      commonName: "Oceanic Manta Ray",
      scientificName: "Mobula birostris",
      status: "VULNERABLE",
      populationEstimate: 45000,
      populationTrend: "INCREASING",
      primaryHabitat: "Coastal Reef Edges",
      sector: "SEC-B4",
      lastSighting: "2026-07-23T18:02:12Z",
      taggedIndividuals: 84,
      migrationStatus: "Local Feeding Aggregation",
      threatLevel: "LOW",
      imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
      description: "Aggregating near Sector B4 cleaning stations. Zero plastic ingestions detected this quarter."
    },
    {
      id: "SPC-004",
      commonName: "Giant Deep-Sea Squid",
      scientificName: "Architeuthis dux",
      status: "LEAST_CONCERN",
      populationEstimate: 120000,
      populationTrend: "STABLE",
      primaryHabitat: "Bathypelagic / Abyssal",
      sector: "SEC-C1",
      lastSighting: "2026-07-23T16:20:00Z",
      taggedIndividuals: 12,
      migrationStatus: "Deep Trench Resident",
      threatLevel: "LOW",
      imageUrl: "https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?auto=format&fit=crop&w=800&q=80",
      description: "Bioluminescent signaling detected at 1,840 meters depth by ROV Abyssal Watcher."
    }
  ],

  sectors: [
    {
      id: "SEC-A1",
      name: "Northern Coral Archipelago",
      bounds: [[14.25, 72.55], [14.45, 72.75]],
      center: [14.35, 72.65],
      riskLevel: "LOW",
      activeDronesCount: 1,
      coralCoveragePct: 72.3,
      waterTempC: 27.2,
      depthMeters: 45,
      salinityPSU: 35.0,
      pollutionLevel: "LOW",
      currentStatus: "STABLE",
      assignedDrone: "DR-007",
      nearestBuoy: "SB-001",
      weatherStation: "WS-001",
      reefCount: 8,
      speciesCount: 42,
      notes: "Pristine coral ecosystem with high biodiversity index."
    },
    {
      id: "SEC-A2",
      name: "North Barrier Coral Trench",
      bounds: [[14.05, 72.75], [14.25, 72.95]],
      center: [14.15, 72.85],
      riskLevel: "LOW",
      activeDronesCount: 2,
      coralCoveragePct: 68.4,
      waterTempC: 27.8,
      notes: "High coral diversity zone. Protected marine sanctuary boundary."
    },
    {
      id: "SEC-A3",
      name: "Eastern Migration Corridor",
      bounds: [[13.85, 72.95], [14.05, 73.15]],
      center: [13.95, 73.05],
      riskLevel: "LOW",
      activeDronesCount: 1,
      coralCoveragePct: 54.7,
      waterTempC: 28.1,
      depthMeters: 85,
      salinityPSU: 35.1,
      pollutionLevel: "LOW",
      currentStatus: "STABLE",
      assignedDrone: "DR-005",
      nearestBuoy: "SB-003",
      weatherStation: "WS-002",
      reefCount: 4,
      speciesCount: 35,
      notes: "Major whale migration route. Seasonal feeding grounds."
    },
    {
      id: "SEC-A4",
      name: "Northeast Seamount Ridge",
      bounds: [[13.65, 73.15], [13.85, 73.35]],
      center: [13.75, 73.25],
      riskLevel: "MODERATE",
      activeDronesCount: 1,
      coralCoveragePct: 41.2,
      waterTempC: 28.4,
      depthMeters: 120,
      salinityPSU: 35.3,
      pollutionLevel: "MODERATE",
      currentStatus: "MONITORING",
      assignedDrone: "DR-008",
      nearestBuoy: "SB-004",
      weatherStation: "WS-002",
      reefCount: 3,
      speciesCount: 28,
      notes: "Underwater seamount complex with unique deep-water species."
    },
    {
      id: "SEC-A5",
      name: "Coastal Mangrove Transition",
      bounds: [[13.45, 73.35], [13.65, 73.55]],
      center: [13.55, 73.45],
      riskLevel: "LOW",
      activeDronesCount: 1,
      coralCoveragePct: 38.9,
      waterTempC: 28.8,
      depthMeters: 25,
      salinityPSU: 34.8,
      pollutionLevel: "MODERATE",
      currentStatus: "STABLE",
      assignedDrone: "DR-009",
      nearestBuoy: "SB-005",
      weatherStation: "WS-003",
      reefCount: 5,
      speciesCount: 45,
      notes: "Mangrove-coral ecotone with high juvenile fish populations."
    },
    {
      id: "SEC-B1",
      name: "Central Basin Deep Zone",
      bounds: [[13.25, 72.65], [13.45, 72.85]],
      center: [13.35, 72.75],
      riskLevel: "MODERATE",
      activeDronesCount: 1,
      coralCoveragePct: 22.4,
      waterTempC: 29.2,
      depthMeters: 450,
      salinityPSU: 35.5,
      pollutionLevel: "MODERATE",
      currentStatus: "MONITORING",
      assignedDrone: "DR-010",
      nearestBuoy: "SB-006",
      weatherStation: "WS-004",
      reefCount: 2,
      speciesCount: 18,
      notes: "Deep basin with cold water upwelling events."
    },
    {
      id: "SEC-B2",
      name: "Mid-Ocean Ridge Section",
      bounds: [[13.05, 72.85], [13.25, 73.05]],
      center: [13.15, 72.95],
      riskLevel: "MODERATE",
      activeDronesCount: 1,
      coralCoveragePct: 35.6,
      waterTempC: 28.9,
      depthMeters: 280,
      salinityPSU: 35.4,
      pollutionLevel: "LOW",
      currentStatus: "STABLE",
      assignedDrone: "DR-011",
      nearestBuoy: "SB-007",
      weatherStation: "WS-004",
      reefCount: 4,
      speciesCount: 32,
      notes: "Geologically active ridge with hydrothermal vent communities."
    },
    {
      id: "SEC-B3",
      name: "Western Shipping Lane",
      bounds: [[12.85, 73.05], [13.05, 73.25]],
      center: [12.95, 73.15],
      riskLevel: "HIGH",
      activeDronesCount: 2,
      coralCoveragePct: 28.7,
      waterTempC: 29.5,
      depthMeters: 95,
      salinityPSU: 35.2,
      pollutionLevel: "HIGH",
      currentStatus: "ALERT",
      assignedDrone: "DR-012",
      nearestBuoy: "SB-008",
      weatherStation: "WS-005",
      reefCount: 3,
      speciesCount: 24,
      notes: "Heavy commercial vessel traffic. High pollution monitoring priority."
    },
    {
      id: "SEC-B4",
      name: "Central Equatorial Ridge",
      bounds: [[12.65, 73.25], [12.85, 73.45]],
      center: [12.75, 73.35],
      riskLevel: "MODERATE",
      activeDronesCount: 3,
      coralCoveragePct: 45.2,
      waterTempC: 28.5,
      notes: "Commercial shipping overlap zone. High surveillance priority."
    },
    {
      id: "SEC-B5",
      name: "Southern Plateau Edge",
      bounds: [[12.45, 73.45], [12.65, 73.65]],
      center: [12.55, 73.55],
      riskLevel: "LOW",
      activeDronesCount: 1,
      coralCoveragePct: 58.3,
      waterTempC: 28.2,
      depthMeters: 55,
      salinityPSU: 35.0,
      pollutionLevel: "LOW",
      currentStatus: "STABLE",
      assignedDrone: "DR-013",
      nearestBuoy: "SB-010",
      weatherStation: "WS-006",
      reefCount: 7,
      speciesCount: 41,
      notes: "Plateau edge with healthy coral gardens."
    },
    {
      id: "SEC-C1",
      name: "Southern Abyssal Trench",
      bounds: [[12.25, 73.65], [12.45, 73.85]],
      center: [12.35, 73.75],
      riskLevel: "HIGH",
      activeDronesCount: 1,
      coralCoveragePct: 12.1,
      waterTempC: 30.1,
      notes: "Deep trench thermal anomaly area with chemical vessel traffic."
    }
  ],

  alerts: [
    {
      id: "ALR-001",
      title: "Ghost Net Entanglement Risk Flagged",
      category: "POLLUTION",
      severity: "CRITICAL",
      sector: "SEC-B4",
      latitude: 12.9281,
      longitude: 73.1499,
      timestamp: "2026-07-23T18:15:32Z",
      read: false,
      archived: false,
      description: "Drone DR-001 identified a 14m commercial fishing net drifting near Hawksbill turtle migration route.",
      actionRequired: "Deploy Vessel Alpha Recovery Team"
    },
    {
      id: "ALR-002",
      title: "Micro-Plastic Accumulation Detected",
      category: "POLLUTION",
      severity: "HIGH",
      sector: "SEC-A2",
      latitude: 14.1205,
      longitude: 72.8512,
      timestamp: "2026-07-23T17:42:10Z",
      read: false,
      archived: false,
      description: "Detection DET-002 identified micro-plastic accumulation slick of 450m radius. Ocean Skimmer Drone Fleet notified.",
      actionRequired: "Monitor cleanup operation",
      detectionId: "DET-002"
    },
    {
      id: "ALR-003",
      title: "Benthic Fuel Oil Residue Alert",
      category: "CHEMICAL_SPILL",
      severity: "HIGH",
      sector: "SEC-C1",
      latitude: 11.4620,
      longitude: 74.2255,
      timestamp: "2026-07-23T16:20:00Z",
      read: false,
      archived: false,
      description: "Surface temperature exceeded 30.0°C threshold for 48 consecutive hours.",
      actionRequired: "Trigger Autonomous Shading Drone Protocol"
    },
    {
      id: "ALR-006",
      title: "Hawksbill Sea Turtle Sighting",
      category: "MARINE_LIFE",
      severity: "INFO",
      sector: "SEC-A2",
      latitude: 14.12,
      longitude: 72.85,
      timestamp: "2026-07-23T13:15:00Z",
      read: true,
      archived: false,
      description: "Detection DET-006 documented Hawksbill sea turtle nesting activity.",
      actionRequired: "Monitor for entanglement risks",
      detectionId: "DET-006"
    },
    {
      id: "ALR-007",
      title: "Oceanic Manta Ray Feeding",
      category: "MARINE_LIFE",
      severity: "INFO",
      sector: "SEC-B4",
      latitude: 12.93,
      longitude: 73.15,
      timestamp: "2026-07-23T12:00:00Z",
      read: true,
      archived: false,
      description: "Drone DR-004 battery dropped below 30%. Initiating automatic return to charging dock.",
      actionRequired: "Docking procedure complete"
    }
  ],

  liveEvents: [
    {
      id: "EV-901",
      time: "18:24:10",
      type: "POLLUTION_DETECTED",
      title: "Ghost Net Detected",
      sector: "Sector SEC-B4",
      confidence: "96.4%",
      severity: "CRITICAL"
    },
    {
      id: "EV-902",
      time: "18:20:05",
      type: "DRONE_TELEMETRY",
      title: "Drone DR-003 reached waypoint",
      sector: "Abyssal Trench SEC-C1",
      confidence: "100%",
      severity: "INFO"
    },
    {
      id: "EV-903",
      time: "18:15:30",
      type: "CORAL_ALERT",
      title: "Coral thermal threshold alert",
      sector: "Sector SEC-C1",
      confidence: "92.0%",
      severity: "WARNING"
    },
    {
      id: "EV-904",
      time: "18:02:12",
      type: "SPECIES_SPOTTED",
      title: "Blue Whale Pod Identified",
      sector: "Sector SEC-A3",
      confidence: "98.9%",
      severity: "INFO"
    }
  ],

  weather: {
    sector: "SEC-B4",
    waveHeightMeters: 1.4,
    wavePeriodSec: 7.2,
    windSpeedKnots: 12.8,
    windDirection: "NE",
    airTempC: 28.5,
    waterTempC: 27.2,
    salinityPSU: 35.1,
    pHLevel: 8.12,
    dissolvedOxygenMgL: 6.9,
    visibilityMeters: 28.0,
    stormProbabilityPct: 8.5,
    forecast24h: [
      { hour: "00:00", wave: 1.2, temp: 26.8, wind: 10.2 },
      { hour: "04:00", wave: 1.1, temp: 26.5, wind: 9.8 },
      { hour: "08:00", wave: 1.3, temp: 27.4, wind: 11.5 },
      { hour: "12:00", wave: 1.5, temp: 28.5, wind: 13.2 },
      { hour: "16:00", wave: 1.6, temp: 28.1, wind: 14.0 },
      { hour: "20:00", wave: 1.4, temp: 27.2, wind: 12.0 }
    ]
  },

  analytics: {
    pollutionTrend: [
      { month: "Jan", plastics: 240, oilSlicks: 45, ghostNets: 18, chemicalSpills: 12 },
      { month: "Feb", plastics: 210, oilSlicks: 38, ghostNets: 15, chemicalSpills: 10 },
      { month: "Mar", plastics: 195, oilSlicks: 30, ghostNets: 12, chemicalSpills: 8 },
      { month: "Apr", plastics: 180, oilSlicks: 25, ghostNets: 14, chemicalSpills: 9 },
      { month: "May", plastics: 160, oilSlicks: 22, ghostNets: 10, chemicalSpills: 7 },
      { month: "Jun", plastics: 142, oilSlicks: 18, ghostNets: 8, chemicalSpills: 6 },
      { month: "Jul", plastics: 135, oilSlicks: 16, ghostNets: 7, chemicalSpills: 5 },
      { month: "Aug", plastics: 128, oilSlicks: 14, ghostNets: 6, chemicalSpills: 4 },
      { month: "Sep", plastics: 145, oilSlicks: 17, ghostNets: 8, chemicalSpills: 6 },
      { month: "Oct", plastics: 158, oilSlicks: 20, ghostNets: 10, chemicalSpills: 8 },
      { month: "Nov", plastics: 175, oilSlicks: 24, ghostNets: 12, chemicalSpills: 10 },
      { month: "Dec", plastics: 195, oilSlicks: 28, ghostNets: 14, chemicalSpills: 11 }
    ],
    coralHealthMonthly: [
      { month: "Jan", index: 81.2, bleachingRisk: 12.4, algaeGrowth: 15.8, fishDensity: 78 },
      { month: "Feb", index: 82.0, bleachingRisk: 10.8, algaeGrowth: 14.5, fishDensity: 80 },
      { month: "Mar", index: 82.8, bleachingRisk: 9.5, algaeGrowth: 13.2, fishDensity: 82 },
      { month: "Apr", index: 83.1, bleachingRisk: 8.9, algaeGrowth: 12.8, fishDensity: 83 },
      { month: "May", index: 83.9, bleachingRisk: 7.2, algaeGrowth: 11.5, fishDensity: 85 },
      { month: "Jun", index: 84.2, bleachingRisk: 6.8, algaeGrowth: 10.2, fishDensity: 86 },
      { month: "Jul", index: 83.8, bleachingRisk: 7.5, algaeGrowth: 11.8, fishDensity: 84 },
      { month: "Aug", index: 83.2, bleachingRisk: 8.2, algaeGrowth: 12.5, fishDensity: 82 },
      { month: "Sep", index: 83.5, bleachingRisk: 7.8, algaeGrowth: 12.0, fishDensity: 83 },
      { month: "Oct", index: 84.0, bleachingRisk: 7.0, algaeGrowth: 11.2, fishDensity: 85 },
      { month: "Nov", index: 84.5, bleachingRisk: 6.5, algaeGrowth: 10.5, fishDensity: 87 },
      { month: "Dec", index: 84.8, bleachingRisk: 6.2, algaeGrowth: 10.0, fishDensity: 88 }
    ],
    speciesGrowth: [
      { year: "2022", blueWhales: 38, seaTurtles: 82, mantaRays: 60, hammerheads: 45, dolphins: 120 },
      { year: "2023", blueWhales: 41, seaTurtles: 94, mantaRays: 72, hammerheads: 52, dolphins: 135 },
      { year: "2024", blueWhales: 44, seaTurtles: 101, mantaRays: 78, hammerheads: 58, dolphins: 148 },
      { year: "2025", blueWhales: 46, seaTurtles: 108, mantaRays: 81, hammerheads: 63, dolphins: 158 },
      { year: "2026", blueWhales: 48, seaTurtles: 112, mantaRays: 84, hammerheads: 67, dolphins: 165 }
    ],
    droneMissionsCompleted: [
      { category: "Plastic Survey", count: 142, successRate: 94.2 },
      { category: "Reef Bleaching", count: 98, successRate: 91.5 },
      { category: "Species Tagging", count: 76, successRate: 88.0 },
      { category: "Trench Bathymetry", count: 45, successRate: 96.8 },
      { category: "Oil Containment", count: 28, successRate: 89.3 },
      { category: "Ghost Net Recovery", count: 35, successRate: 92.7 },
      { category: "Water Quality", count: 62, successRate: 95.1 },
      { category: "Seismic Monitoring", count: 18, successRate: 97.5 }
    ],
    sectorPerformance: [
      { sector: "SEC-A1", healthScore: 87, pollutionIndex: 12, biodiversity: 92 },
      { sector: "SEC-A2", healthScore: 91, pollutionIndex: 8, biodiversity: 95 },
      { sector: "SEC-A3", healthScore: 89, pollutionIndex: 10, biodiversity: 94 },
      { sector: "SEC-A4", healthScore: 85, pollutionIndex: 14, biodiversity: 88 },
      { sector: "SEC-A5", healthScore: 82, pollutionIndex: 16, biodiversity: 86 },
      { sector: "SEC-B1", healthScore: 88, pollutionIndex: 11, biodiversity: 90 },
      { sector: "SEC-B2", healthScore: 79, pollutionIndex: 18, biodiversity: 82 },
      { sector: "SEC-B3", healthScore: 83, pollutionIndex: 15, biodiversity: 87 },
      { sector: "SEC-B4", healthScore: 86, pollutionIndex: 13, biodiversity: 89 },
      { sector: "SEC-B5", healthScore: 81, pollutionIndex: 17, biodiversity: 85 },
      { sector: "SEC-C1", healthScore: 90, pollutionIndex: 9, biodiversity: 93 },
      { sector: "SEC-C2", healthScore: 84, pollutionIndex: 14, biodiversity: 86 },
      { sector: "SEC-C3", healthScore: 87, pollutionIndex: 12, biodiversity: 91 },
      { sector: "SEC-C4", healthScore: 82, pollutionIndex: 16, biodiversity: 84 },
      { sector: "SEC-C5", healthScore: 80, pollutionIndex: 19, biodiversity: 83 },
      { sector: "SEC-D1", healthScore: 92, pollutionIndex: 7, biodiversity: 96 },
      { sector: "SEC-D2", healthScore: 85, pollutionIndex: 13, biodiversity: 88 },
      { sector: "SEC-D3", healthScore: 83, pollutionIndex: 15, biodiversity: 86 },
      { sector: "SEC-D4", healthScore: 88, pollutionIndex: 11, biodiversity: 90 },
      { sector: "SEC-D5", healthScore: 89, pollutionIndex: 10, biodiversity: 92 },
      { sector: "SEC-E1", healthScore: 78, pollutionIndex: 20, biodiversity: 80 },
      { sector: "SEC-E2", healthScore: 80, pollutionIndex: 18, biodiversity: 82 },
      { sector: "SEC-E3", healthScore: 76, pollutionIndex: 22, biodiversity: 78 },
      { sector: "SEC-E4", healthScore: 82, pollutionIndex: 15, biodiversity: 85 },
      { sector: "SEC-E5", healthScore: 84, pollutionIndex: 14, biodiversity: 87 }
    ],
    monthlyDetections: [
      { month: "Jan", total: 145, critical: 18, high: 42, moderate: 55, low: 30 },
      { month: "Feb", total: 132, critical: 15, high: 38, moderate: 52, low: 27 },
      { month: "Mar", total: 128, critical: 12, high: 35, moderate: 50, low: 31 },
      { month: "Apr", total: 118, critical: 14, high: 32, moderate: 46, low: 26 },
      { month: "May", total: 105, critical: 10, high: 28, moderate: 42, low: 25 },
      { month: "Jun", total: 98, critical: 8, high: 25, moderate: 40, low: 25 },
      { month: "Jul", total: 92, critical: 7, high: 22, moderate: 38, low: 25 },
      { month: "Aug", total: 88, critical: 6, high: 20, moderate: 36, low: 26 },
      { month: "Sep", total: 95, critical: 8, high: 24, moderate: 38, low: 25 },
      { month: "Oct", total: 108, critical: 10, high: 28, moderate: 42, low: 28 },
      { month: "Nov", total: 122, critical: 12, high: 32, moderate: 48, low: 30 },
      { month: "Dec", total: 138, critical: 14, high: 36, moderate: 52, low: 36 }
    ]
  },

  oceanFacts: [
    { id: "OF-001", category: "Biodiversity", fact: "The ocean produces over 50% of the world's oxygen through phytoplankton photosynthesis." },
    { id: "OF-002", category: "Geography", fact: "The ocean covers more than 70% of Earth's surface and contains 97% of its water." },
    { id: "OF-003", category: "Marine Life", fact: "Blue whales are the largest animals ever known to exist, reaching lengths of up to 30 meters." },
    { id: "OF-004", category: "Ecosystems", fact: "Coral reefs support 25% of all marine species despite covering less than 1% of the ocean floor." },
    { id: "OF-005", category: "Climate", fact: "The ocean absorbs about 90% of excess heat from global warming." },
    { id: "OF-006", category: "Exploration", fact: "Less than 20% of the ocean has been mapped and explored by humans." },
    { id: "OF-007", category: "Marine Life", fact: "Octopuses have three hearts and blue blood due to copper-based hemocyanin." },
    { id: "OF-008", category: "Geography", fact: "The Mariana Trench is the deepest part of the ocean, reaching depths of 11,034 meters." },
    { id: "OF-009", category: "Biodiversity", fact: "There are an estimated 230,000 known marine species, with potentially millions more undiscovered." },
    { id: "OF-010", category: "Climate", fact: "Ocean currents regulate global climate by distributing heat around the planet." },
    { id: "OF-011", category: "Marine Life", fact: "Sea turtles can hold their breath for up to 7 hours while resting underwater." },
    { id: "OF-012", category: "Ecosystems", fact: "Mangrove forests protect coastlines from erosion and serve as nurseries for fish." },
    { id: "OF-013", category: "Geography", fact: "The Great Barrier Reef is visible from space and spans over 2,300 kilometers." },
    { id: "OF-014", category: "Marine Life", fact: "Dolphins sleep with one eye open and half their brain awake to watch for predators." },
    { id: "OF-015", category: "Climate", fact: "The ocean has absorbed about 30% of human-generated carbon dioxide since the Industrial Revolution." },
    { id: "OF-016", category: "Biodiversity", fact: "Sponges are among the oldest living animals, with some species living over 10,000 years." },
    { id: "OF-017", category: "Marine Life", fact: "Sharks have been around for over 400 million years, predating dinosaurs." },
    { id: "OF-018", category: "Ecosystems", fact: "Seagrass meadows capture carbon up to 35 times faster than tropical rainforests." },
    { id: "OF-019", category: "Geography", fact: "The ocean contains an estimated 20 million tons of gold, mostly in microscopic particles." },
    { id: "OF-020", category: "Marine Life", fact: "Jellyfish are 95% water and have no brain, heart, or bones." },
    { id: "OF-021", category: "Climate", fact: "Sea levels have risen about 23 centimeters since 1880 due to melting ice and thermal expansion." },
    { id: "OF-022", category: "Biodiversity", fact: "The ocean is home to the largest living structure on Earth: the Great Barrier Reef." },
    { id: "OF-023", category: "Marine Life", fact: "Manta rays have the largest brain-to-body ratio of all fish." },
    { id: "OF-024", category: "Ecosystems", fact: "Kelp forests grow up to 60 centimeters per day, making them the fastest-growing organisms." },
    { id: "OF-025", category: "Geography", fact: "The ocean contains 99% of Earth's living space by volume." },
    { id: "OF-026", category: "Marine Life", fact: "Seahorses are the only species where males give birth to young." },
    { id: "OF-027", category: "Climate", fact: "Ocean acidification has increased by 30% since pre-industrial times due to CO2 absorption." },
    { id: "OF-028", category: "Biodiversity", fact: "More than 80% of the ocean remains unmapped and unexplored." },
    { id: "OF-029", category: "Marine Life", fact: "Clownfish can change their sex from male to female during their lifetime." },
    { id: "OF-030", category: "Ecosystems", fact: "Deep-sea vents support entire ecosystems without sunlight, using chemosynthesis." },
    { id: "OF-031", category: "Geography", fact: "The Pacific Ocean is larger than all Earth's landmasses combined." },
    { id: "OF-032", category: "Marine Life", fact: "Whale sharks can filter up to 1,500 gallons of water per hour while feeding." },
    { id: "OF-033", category: "Climate", fact: "The ocean stores about 50 times more carbon than the atmosphere." },
    { id: "OF-034", category: "Biodiversity", fact: "A single coral colony can consist of thousands of individual polyps." },
    { id: "OF-035", category: "Marine Life", fact: "Hammerhead sharks have 360-degree vision due to their uniquely shaped heads." },
    { id: "OF-036", category: "Ecosystems", fact: "Salt marshes can store carbon 10 times faster per acre than tropical forests." },
    { id: "OF-037", category: "Geography", fact: "The longest mountain range on Earth is underwater: the Mid-Ocean Ridge." },
    { id: "OF-038", category: "Marine Life", fact: "Parrotfish play a crucial role in coral reef health by eating algae." },
    { id: "OF-039", category: "Climate", fact: "The ocean regulates Earth's temperature by absorbing and releasing heat slowly." },
    { id: "OF-040", category: "Biodiversity", fact: "Marine plankton produce more oxygen than all rainforests combined." },
    { id: "OF-041", category: "Marine Life", fact: "Sea otters have the densest fur of any animal, with up to 1 million hairs per square inch." },
    { id: "OF-042", category: "Ecosystems", fact: "Coral reefs protect coastlines from waves and storms, reducing damage by up to 97%." },
    { id: "OF-043", category: "Geography", fact: "The ocean contains about 1.3 billion cubic kilometers of water." },
    { id: "OF-044", category: "Marine Life", fact: "Electric eels can generate shocks of up to 860 volts to stun prey." },
    { id: "OF-045", category: "Climate", fact: "Ocean temperatures have risen by about 1.5°F since 1900." },
    { id: "OF-046", category: "Biodiversity", fact: "The ocean is home to the largest animal migration: the daily vertical migration of zooplankton." },
    { id: "OF-047", category: "Marine Life", fact: "Starfish can regenerate lost limbs and can even grow a new body from a single limb." },
    { id: "OF-048", category: "Ecosystems", fact: "Wetlands filter pollutants and protect water quality for coastal communities." },
    { id: "OF-049", category: "Geography", fact: "The ocean floor moves at about the same rate as fingernails grow due to tectonic activity." },
    { id: "OF-050", category: "Marine Life", fact: "Narwhals' tusks are actually elongated teeth that can grow up to 3 meters long." }
  ],

  systemHealth: {
    overallStatus: "OPERATIONAL",
    uptime: "99.97%",
    lastRestart: "2026-07-15T03:00:00Z",
    components: {
      apiGateway: { status: "HEALTHY", responseTime: 45, uptime: "99.99%" },
      database: { status: "HEALTHY", responseTime: 12, uptime: "100%", connections: 45 },
      aiProcessing: { status: "HEALTHY", responseTime: 180, uptime: "99.95%", queueDepth: 3 },
      droneComms: { status: "HEALTHY", responseTime: 85, uptime: "99.92%", activeDrones: 17 },
      sensorNetwork: { status: "HEALTHY", responseTime: 30, uptime: "99.98%", activeSensors: 12 },
      dataPipeline: { status: "HEALTHY", throughput: "2.4GB/hr", uptime: "99.96%" },
      storage: { status: "HEALTHY", capacity: "78%", used: "6.2TB", available: "1.8TB" },
      cache: { status: "HEALTHY", hitRate: "94.2%", memoryUsage: "67%" }
    },
    alerts: {
      critical: 0,
      warning: 2,
      info: 5
    },
    performance: {
      cpuUsage: 42,
      memoryUsage: 68,
      diskIO: 23,
      networkIO: 45
    },
    lastHealthCheck: "2026-07-23T18:00:00Z"
  },

  riskEngine: {
    overallRiskScore: 32,
    riskRating: "LOW_TO_MODERATE",
    aiConfidence: 94.8,
    forecasts: {
      pollutionDispersalRisk: 28,
      coralBleachingProbability: 18,
      stormImpactSeverity: 14,
      speciesHabitatLoss: 12
    },
    recommendations: [
      {
        id: "REC-01",
        title: "Deploy Automated Skim Drones in Sector B4",
        priority: "HIGH",
        impact: "Reduces surface microplastic aggregation by 35% within 48 hours."
      },
      {
        id: "REC-02",
        title: "Activate Deep Thermal Shading Net in Sector C1",
        priority: "MEDIUM",
        impact: "Mitigates surface thermal stress on bleaching barrier reefs."
      }
    ]
  },

  profile: {
    id: "USR-9901",
    name: "Dr. Elena Rostova",
    role: "Lead Oceanographer & Chief Marine Scientist",
    organization: "Global Oceanographic Research Institute (GORI)",
    email: "elena.rostova@oceaneye.org",
    location: "Kiel Marine Station / Offshore Vessel Alpha",
    missionHours: 1420,
    reportsGenerated: 86,
    certifications: [
      "Deep Sea Submersible Mission Commander (FAA/IMO)",
      "AI Computer Vision Marine Specialist Level III",
      "GIS Marine Ecosystem Analyst"
    ],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80"
  },

  settings: {
    theme: "dark",
    autoRefreshIntervalSec: 15,
    notificationsEnabled: true,
    audioAlerts: true,
    units: {
      depth: "feet",
      temperature: "celsius",
      speed: "knots"
    },
    mapProvider: "CartoDB Dark Matter",
    developerMode: true,
    apiKey: "oe_live_99841029837410928374"
  }
};

module.exports = mockStore;


